version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 24203@IIITU.ac.in
      POSTGRES_DB: peblo_mini
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:24203%40IIITU.ac.in@db:5432/peblo_mini
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./assets:/app/assets

  cms:
    build:
      context: ./frontend/cms
    ports:
      - "3000:80"
    depends_on:
      - backend

  viewer:
    build:
      context: ./frontend/viewer
    ports:
      - "4000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
